"use server";

const pinataSDK = require("@pinata/sdk");

export async function uploadJSONToIPFS(json: any) {
  const pinata = new pinataSDK({ pinataJWTKey: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mb3JtYXRpb24iOnsiaWQiOiJkZmI0MmM3Ny01MjdmLTQyMDMtODM1Yy04YzU0NTlkMTdkOTciLCJlbWFpbCI6ImEubmFkYXJhc2FAbmhzLm5ldCIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJwaW5fcG9saWN5Ijp7InJlZ2lvbnMiOlt7ImRlc2lyZWRSZXBsaWNhdGlvbkNvdW50IjoxLCJpZCI6IkZSQTEifSx7ImRlc2lyZWRSZXBsaWNhdGlvbkNvdW50IjoxLCJpZCI6Ik5ZQzEifV0sInZlcnNpb24iOjF9LCJtZmFfZW5hYmxlZCI6ZmFsc2UsInN0YXR1cyI6IkFDVElWRSJ9LCJhdXRoZW50aWNhdGlvblR5cGUiOiJzY29wZWRLZXkiLCJzY29wZWRLZXlLZXkiOiJhNzBiYmU4NmZmNmNhNDFiM2ZiMyIsInNjb3BlZEtleVNlY3JldCI6IjYzNTRiM2ExMWFhNTNjNzBhZTQxNjgzM2IzMDcxZDIwYjE5NTE0ODU5MTI1YjRkZTc3MDg5NTAzMjVjZGNkODgiLCJleHAiOjE3NjAyOTYzODR9.LA1BAQk-DeQzHlgAfUDJmryOyrvMN5iPwHzKG2gyolc" });
  const res = await pinata.pinJSONToIPFS(json);
  return res.IpfsHash;
}
